config/routes.rb
Rails.application.routes.draw do
  resources :issues
  resources :repositories
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :repository
  belongs_to :user
end

app/models/repository.rb
class Repository < ApplicationRecord
    belongs_to :user
    has_many :issues, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord

  has_many :repositories, dependent: :destroy
  has_many :issues, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


         validates :username, presence: :true, uniqueness: { case_sensitive: false }

         validates_format_of :username, with: /^[a-zA-Z]*$/, :multiline => true


         attr_writer :login

         def login
           @login || self.username || self.email 
         end



        # def self.find_for_database_authentication(warden_conditions)
         # conditions = warden_conditions.dup
          #if login = conditions.delete(:login)
          #  where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
          #elsif conditions.has_key?(:username) || conditions.has_key?(:email)
          #  where(conditions.to_h).first
          #end
        #end

        def self.find_first_by_auth_conditions(warden_conditions)
          conditions = warden_conditions.dup
          if login = conditions.delete(:login)
            where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
          else
            if conditions[:username].nil?
              where(conditions).first
            else
              where(username: conditions[:username]).first
            end
          end
        end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            added_attrs = [:name, :username, :email, :password, :password_confirmation, :remember_me]
            devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
            devise_parameter_sanitizer.permit :account_update, keys: added_attrs
        end

        #devise_parameter_sanitizer.for(:sign_up).push(:username) 
        #devise_parameter_sanitizer.permit(:sign_up, keys: [:username])


end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    @issue = Issue.new
    @issue_user_id = current_user.id
    @issue_repository_id = 1
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    #@issue = Issue.new(issue_params)
    @issue = current_user.issues.new(issue_params)
    
    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:subject, :text, :user, :repository_id)
    end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :set_repository, only: [:show, :edit, :update, :destroy]

  # GET /repositories
  # GET /repositories.json
  def index
    @repositories = Repository.all
  end

  # GET /repositories/1
  # GET /repositories/1.json
  def show
  end

  # GET /repositories/new
  def new
    @repository = Repository.new
    @repository_user_id = current_user.id
  end

  # GET /repositories/1/edit
  def edit
  end

  # POST /repositories
  # POST /repositories.json
  def create
    #@repository = Repository.new(repository_params)
    @repository = current_user.repositories.new(repository_params)
    respond_to do |format|
      if @repository.save
        format.html { redirect_to @repository, notice: 'Repository was successfully created.' }
        format.json { render :show, status: :created, location: @repository }
      else
        format.html { render :new }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repositories/1
  # PATCH/PUT /repositories/1.json
  def update
    respond_to do |format|
      if @repository.update(repository_params)
        format.html { redirect_to @repository, notice: 'Repository was successfully updated.' }
        format.json { render :show, status: :ok, location: @repository }
      else
        format.html { render :edit }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repositories/1
  # DELETE /repositories/1.json
  def destroy
    @repository.destroy
    respond_to do |format|
      format.html { redirect_to repositories_url, notice: 'Repository was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repository
      @repository = Repository.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repository_params
      params.require(:repository).permit(:name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/issues/_form.html.erb
<%= form_with(model: issue, local: true) do |form| %>
  <% if issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
        <% issue.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>


  <%= form.label :repository_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= form.select :repository_id, current_user.repositories.pluck(:name, :id), {}, class: "form-control" %>
    </div>
 

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing Issue</h1>

<%= render 'form', issue: @issue %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Issues</h1>

<% if user_signed_in? %>
  Logged in as <strong><%= current_user.username %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>

  <table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Text</th>
      <th>Author</th>
      <th>Repository</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= issue.subject %></td>
        <td><%= issue.text %></td>
        <td><%= issue.user.username %></td>
        <td><%= issue.repository.name %></td>
        <td><%= link_to 'Show', issue %></td>
        <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
        <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<font size="3"><%= link_to 'New Issue', new_issue_path %></font>
<p></p>
<font size="3"><%= link_to 'My Repositories', repositories_path %></font>
<p></p>
<font size="3"><%= link_to 'Homepage', root_path %></font>
 
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

app/views/issues/new.html.erb
<h1>New Issue</h1>

<%= render 'form', issue: @issue %>

<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @issue.subject %>
</p>

<p>
  <strong>Text:</strong>
  <%= @issue.text %>
</p>

<p>
  <strong>Author:</strong>
  <%= @issue.user.username %>
</p>

<p>
  <strong>Repository ID:</strong>
  <%= @issue.repository_id %>
</p>

<p>
  <strong>Repository Name:</strong>
  <%= @issue.repository.name %>
</p>

<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMuniHub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/repositories/_form.html.erb
<%= form_with(model: repository, local: true) do |form| %>
  <% if repository.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(repository.errors.count, "error") %> prohibited this repository from being saved:</h2>

      <ul>
        <% repository.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/repositories/edit.html.erb
<h1>Editing Repository</h1>

<%= render 'form', repository: @repository %>

<%= link_to 'Show', @repository %> |
<%= link_to 'Back', repositories_path %>

app/views/repositories/index.html.erb
<p id="notice"><%= notice %></p>

<% if user_signed_in? %>
  Logged in as <strong><%= current_user.username %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>


  <h1>My Repositories</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="0.5"></th>
        <th>Owner</th>
        <th colspan="1"></th>
      </tr>
  
  
  
    </thead>
  
    <tbody>
      <% current_user.repositories.each do |repository| %>
        <tr>
          <td><%= repository.name %></td>
          <td><%= current_user.username %></td>
          <td><%= link_to 'Show', repository %></td>
          <td><%= link_to 'Edit', edit_repository_path(repository) %></td>
          <td><%= link_to 'Destroy', repository, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </tbody>
  </table>
  
  <br>
  
  <font size="3"><%= link_to 'New Repository', new_repository_path %></font>
  <p></p>
  <font size="3"><%= link_to 'My Issues', issues_path %></font>
  <p></p>
  <font size="3"><%= link_to 'Homepage', root_path %></font>
  

 
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

app/views/repositories/new.html.erb
<h1>New Repository</h1>


<%= render 'form', repository: @repository %>

<%= link_to 'Back', repositories_path %>

app/views/repositories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @repository.name %>
</p>

<p>
  <strong>Owner:</strong>
  <%= current_user.username %>
</p>

<%= link_to 'Edit', edit_repository_path(@repository) %> |
<%= link_to 'Back', repositories_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to MuniHub!</h1>
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.username %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>

  <p></p>

  <font size="5"><%= link_to 'Go To My Repositories', repositories_path, :class => 'navbar-link' %></font>
  <p></p>
  <font size="5"><%= link_to 'Go To My Issues', issues_path, :class => 'navbar-link' %></font>

 
<% else %>
  
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>

  

<% end %>